name: üöÄ Build Yubico Authenticator to AppImage

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    name: Build AppImage

    steps:
    - name: üì• Checkout repository
      uses: actions/checkout@v6

    - name: üì¶ Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget tar gzip libfuse2
    - name: üåê Download latest Yubico package
      run: |
        echo "‚¨áÔ∏è Downloading latest Yubico Authenticator from source..."
        wget -q --show-progress https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-latest-linux.tar.gz -O latest.tar.gz
        tar -tf latest.tar.gz | head -n5
        tar -zxvf latest.tar.gz
    - name: üîß Build AppImage
      run: |
        SCRIPT="$GITHUB_WORKSPACE/yubico-generator.sh"
        TAR="$GITHUB_WORKSPACE/latest.tar.gz"
        if [ ! -f "$SCRIPT" ]; then
          echo "‚ùå Script not found!"
          ls -l
          exit 1
        fi
        chmod +x "$SCRIPT"
        export HOME="$GITHUB_WORKSPACE"
        sh "$SCRIPT" "$TAR"
        ARCH=$(uname -m)
        echo "ARCH=$ARCH" >> $GITHUB_ENV
        PACKAGE_FOLDER=$(find "$GITHUB_WORKSPACE" -maxdepth 1 -type d -name "yubico-authenticator-*" | head -n1)
        VERSION=$(basename "$PACKAGE_FOLDER" | sed -E 's/yubico-authenticator-(.*)-linux/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        APPIMAGE_NAME="yubikey-authenticator-${VERSION}-${ARCH}.AppImage"
        if [ ! -f "$GITHUB_WORKSPACE/$APPIMAGE_NAME" ]; then
          echo "‚ùå AppImage no generado!"
          ls -l "$GITHUB_WORKSPACE/YubicoAuthenticator.AppDir" || true
          exit 1
        fi
        echo "‚úÖ AppImage ready: $APPIMAGE_NAME"
        ls -l "$GITHUB_WORKSPACE"
    - name: üöÄ Upload AppImage to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        files: ${{ github.workspace }}/yubikey-authenticator-${{ env.VERSION }}-${{ env.ARCH }}.AppImage
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

